[icon-theme]
name = "Material Icons"

[icon-theme.ui]

[icon-theme.filename]
".vscode" = "icons/vscode.svg"

"CODEOWNERS" = "icons/codeowners.svg"
"CONTRIBUTING" = "icons/contributing.svg"
"README" = "icons/readme.svg"

"Dockerfile" = "icons/docker.svg"
"Cargo.lock" = "icons/rust.svg"
"gitignore" = "icons/git.svg"
"gitattributes" = "icons/git.svg"
"Makefile" = "icons/makefile.svg"
"docs" = "icons/folder-docs.svg"

"go.mod" = "icons/go-mod.svg"

[icon-theme.extension]
"c" = "icons/c.svg"
"cpp" = "icons/cpp.svg"
"c++" = "icons/cpp.svg"
"cs" = "icons/csharp.svg"
"cmake" = "icons/cmake.svg"

"h" = "icons/h.svg"
"hpp" = "icons/hpp.svg"
"h++" = "icons/hpp.svg"

"go" = "icons/go.svg"

"less" = "icons/less.svg"

"js" = "icons/javascript.svg"
"jsx" = "icons/react.svg"

"key" = "icons/key.svg"

"doc" = "icons/word.svg"
"docx" = "icons/word.svg"

"md" = "icons/markdown.svg"

"gitattributes" = "icons/git.svg"
"gitignore" = "icons/git.svg"

"ico" = "icons/image.svg"

"rb" = "icons/ruby.svg"
"rs" = "icons/rust.svg"

"svg" = "icons/svg.svg"
"sass" = "icons/sass.svg"
"sh" = "icons/shell.svg"
"svelte" = "icons/svelte.svg"

"wxs" = "icons/xml.svg"

"ps1" = "icons/powershell.svg"
"plist" = "icons/xml.svg"
"png" = "icons/image.svg"
"py" = "icons/python.svg"
"pptx" = "icons/powerpoint.svg"
"pug" = "icons/pug.svg"

"toml" = "icons/toml.svg"
"tf" = "icons/terraform.svg"
"ts" = "icons/typescript.svg"
"tsx" = "icons/react_ts.svg"

"xml" = "icons/xml.svg"
"xaml" = "icons/xaml.svg"

"vue" = "icons/vue.png"

"wasm" = "icons/webassembly.svg"

"yml" = "icons/yaml.svg"
"yaml" = "icons/yaml.svg"

"zig" = "icons/zig.svg"
"zip" = "icons/zip.svg"